### ISSUE TITLE
请问，用minidp接口外接4K显示器，分辨率能到3840*2160嘛？

### ISSUE THREAD

**Issue by dongguochuan** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-CLOVER#5]
我安装完成显卡驱动后，分辨率只能到2560*1440。
是否要解锁BIOS调整DVMT的大小？

谢谢！

**Comment by CLAY-BIOS** [comment]
> 我安装完成显卡驱动后，分辨率只能到2560*1440。
> 是否要解锁BIOS调整DVMT的大小？
> 
> 谢谢！

我目前已经停止对这个仓库的更新。
你可以尝试使用这个config文件，但不保证有效。
[config.plist.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-CLOVER/files/5222958/config.plist.zip)
或者使用 OC的版本
https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Big-Sur-OpenCore
它一样可以在Catalina中使用

**Comment by dongguochuan** [comment]
好，谢谢，我试试。

**Comment by dongguochuan** [comment]
你好，已经解决了。解锁bios高级菜单，把dvmt改成128m，调整stolenmem超过64m，外接显示器可以达到4k。
谢谢！
