### ISSUE TITLE
大神，x250触屏驱动需要你帮解决

### ISSUE THREAD

**Issue by David3434** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-CLOVER#6]
大神，你好！
我有台x250cpu也是5300，带触屏
用你的clover刚安装后，用usb启动，触屏也能用，其它也正常
但是一旦我把配置文件clover放入硬盘的efi文件后，重启触屏就失效了
我网络上搜索一下子也没找到有关解决触屏的方法，只有你这边有

谢谢！

**Comment by CLAY-BIOS** [comment]
> 大神，你好！
> 我有台x250cpu也是5300，带触屏
> 用你的clover刚安装后，用usb启动，触屏也能用，其它也正常
> 但是一旦我把配置文件clover放入硬盘的efi文件后，重启触屏就失效了
> 我网络上搜索一下子也没找到有关解决触屏的方法，只有你这边有
> 
> 谢谢！

1.请告诉我你的系统版本，10.15要把VoodooI2C.kext和VoodooI2CHID.kext放入 L / E 目录
2.在终端执行以下代码 将结果发送上来

log show --last boot --predicate 'process == "kernel" AND (eventMessage CONTAINS "VoodooI2C" OR eventMessage CONTAINS "VoodooGPIO")' --style syslog --source
Filtering the log data using "process == "kernel" AND (composedMessage CONTAINS "VoodooI2C" OR composedMessage CONTAINS "VoodooGPIO")"
Skipping info and debug messages, pass --info and/or --debug to include.

**Comment by David3434** [comment]
@CLAY-BIOS 
版本是10.15.7
我现在用big sur，也是你的方案[https://github.com/philffm/Lenovo-ThinkPad-X250-Big-Sur-OpenCore](url)，触屏可用，太牛了！
不过我还是想用10.15.7
现在正在重装到10.15.7，回头联系你
感谢！

**Comment by David3434** [comment]
补充下：我的t450s在用你的clover，刚刚查证了l/e目录下没有放那2个驱动文件
但是触屏没有问题，已经使用1个多月了

**Comment by CLAY-BIOS** [comment]
> 补充下：我的t450s在用你的clover，刚刚查证了l/e目录下没有放那2个驱动文件
> 但是触屏没有问题，已经使用1个多月了

这个仓库我已经很久没有更新了，因为Clover有很多的问题。
我建议你使用OpenCore的版本，它支持Big sur和Catalina。
https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Big-Sur-OpenCore
x250理论上可以通用，但我手上没有x250用来测试。

**Comment by David3434** [comment]
好的，我也会去试试，非常感谢！
命令结果来了
Last login: Sat Oct 17 01:32:12 on ttys000
jack@Jacks-MacBook-Pro ~ % log show --last boot --predicate 'process == "kernel" AND (eventMessage CONTAINS "VoodooI2C" OR eventMessage CONTAINS "VoodooGPIO")' --style syslog --source
Filtering the log data using "process == "kernel" AND (composedMessage CONTAINS "VoodooI2C" OR composedMessage CONTAINS "VoodooGPIO")"
Skipping info and debug messages, pass --info and/or --debug to include.
Filtering the log data using "process == "kernel" AND (composedMessage CONTAINS "VoodooI2C" OR composedMessage CONTAINS "VoodooGPIO")"
Skipping info and debug messages, pass --info and/or --debug to include.
Timestamp                       (process)[PID]    
zsh: command not found: Filtering
zsh: command not found: Skipping
jack@Jacks-MacBook-Pro ~ % 

刚刚发现，安装完成，首次启动，触屏可以，再重启，就失效了

**Comment by CLAY-BIOS** [comment]
> 好的，我也会去试试，非常感谢！
> 命令结果来了
> Last login: Sat Oct 17 01:32:12 on ttys000
> jack@Jacks-MacBook-Pro ~ % log show --last boot --predicate 'process == "kernel" AND (eventMessage CONTAINS "VoodooI2C" OR eventMessage CONTAINS "VoodooGPIO")' --style syslog --source
> Filtering the log data using "process == "kernel" AND (composedMessage CONTAINS "VoodooI2C" OR composedMessage CONTAINS "VoodooGPIO")"
> Skipping info and debug messages, pass --info and/or --debug to include.
> Filtering the log data using "process == "kernel" AND (composedMessage CONTAINS "VoodooI2C" OR composedMessage CONTAINS "VoodooGPIO")"
> Skipping info and debug messages, pass --info and/or --debug to include.
> Timestamp (process)[PID]
> zsh: command not found: Filtering
> zsh: command not found: Skipping
> jack@Jacks-MacBook-Pro ~ %
> 
> 刚刚发现，安装完成，首次启动，触屏可以，再重启，就失效了

从命令结果来看没有问题，驱动已经成功加载了。
试试把驱动放入L / E 目录。

**Comment by David3434** [comment]
我现在迫不及待正在重装10.15.7（用opencore)
其实不用重装，copy下efi文件就可以的，才想到，来不及了
😜

**Comment by David3434** [comment]
@CLAY-BIOS 
成功了！太感谢了！
我搞了3天，都没搞成功，搞得寝食难安，你几句话的事情就解决了！
祝你幸福健康！朋友

**Comment by David3434** [comment]
@CLAY-BIOS 
你好，发现待机（sleep)后再回来，触碰就失效了，但是重启就正常了
系统10.15.17 opencore用你的，机器是x250
这个需要哪里设置下吗
谢谢

**Comment by CLAY-BIOS** [comment]
> @CLAY-BIOS
> 你好，发现待机（sleep)后再回来，触碰就失效了，但是重启就正常了
> 系统10.15.17 opencore用你的，机器是x250
> 这个需要哪里设置下吗
> 谢谢

虽然我很想帮你，但我没有X250。
我认为应该是usb的问题，因为触屏和睡眠都和usb有关。
你可以尝试一下这个EFI文件。
[EFI.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-CLOVER/files/5413433/EFI.zip)

**Comment by jack338c** [comment]
:smile: 
好的，非常感谢!
我是因为你的repo才去买的t450s,然后又买了x250

**Comment by David3434** [comment]
😄
好的，非常感谢!
我是因为你的repo才去买的t450s,然后又买了x250
实际上T450S待机后也是触碰失灵，2台机器都是一样的OPENCORE和10.15.7

**Comment by David3434** [comment]
@CLAY-BIOS 
哇，用了你那个文件，现在x250真的可以用了！
服了，大神  :smiley:

**Comment by David3434** [comment]
@CLAY-BIOS 
刚才一激动疏忽了，2台电脑都试过了，原来都只有1个手指可以用触碰，2个手指不能用。但是待机失灵问题确实解决了

然后用你早期的驱动 https://github.com/philffm/Lenovo-ThinkPad-X250-Big-Sur-OpenCore
可以在10.15.7上使用2个手指触屏，但是待机后就失灵了（即使在你的文件基础上**单独加了旧的触屏驱动**，也是触碰2指可以用，但是一样待机失灵）

**Comment by David3434** [comment]
大神，更新了你的最新版本，2个电脑所有问题都解决，那个thinkpad Asistant很赞！非常感谢！
唯一个问题就是dw1820A从linux重启到macos时，无线网卡不能用，需要待机唤醒后才可用，或者关机开机才可用
再次感谢分享！
祝生活愉快！

**Comment by CLAY-BIOS** [comment]
> 大神，更新了你的最新版本，2个电脑所有问题都解决，那个thinkpad Asistant很赞！非常感谢！
> 唯一个问题就是dw1820�A从linux重启到macos时，无线网卡不能用，需要待机唤醒后才可用，或者关机开机才可用
> 再次感谢分享！
> 祝生活愉快！

由于使用了新的触控驱动，解决了一些问题。
linux重启到macos无线网卡不能用这个问题是关于热启动的，目前没有办法解决。
还有，你能帮我测试一下是否有以下问题。
1.触摸板拖动文件和图标是否会有卡顿？
2.在MAC下关闭WIFI然后睡眠，唤醒后WIF能否打开？
3.SD卡读卡器是否能够使用？我的SD卡读卡器卡槽坏掉了。

**Comment by David3434** [comment]
好的
迟点回复你

**Comment by David3434** [comment]
> > 大神，更新了你的最新版本，2个电脑所有问题都解决，那个thinkpad Asistant很赞！非常感谢！
> > 唯一个问题就是dw1820�A从linux重启到macos时，无线网卡不能用，需要待机唤醒后才可用，或者关机开机才可用
> > 再次感谢分享！
> > 祝生活愉快！
> 
> 由于使用了新的触控驱动，解决了一些问题。
> linux重启到macos无线网卡不能用这个问题是关于热启动的，目前没有办法解决。
> 还有，你能帮我测试一下是否有以下问题。
> 1.触摸板拖动文件和图标是否会有卡顿？
> 2.在MAC下关闭WIFI然后睡眠，唤醒后WIF能否打开？
> 3.SD卡读卡器是否能够使用？我的SD卡读卡器卡槽坏掉了。

**Comment by David3434** [comment]
> > 大神，更新了你的最新版本，2个电脑所有问题都解决，那个thinkpad Asistant很赞！非常感谢！
> > 唯一个问题就是dw1820�A从linux重启到macos时，无线网卡不能用，需要待机唤醒后才可用，或者关机开机才可用
> > 再次感谢分享！
> > 祝生活愉快！
> 
> 由于使用了新的触控驱动，解决了一些问题。
> linux重启到macos无线网卡不能用这个问题是关于热启动的，目前没有办法解决。
> 还有，你能帮我测试一下是否有以下问题。
> 1.触摸板拖动文件和图标是否会有卡顿？
> 2.在MAC下关闭WIFI然后睡眠，唤醒后WIF能否打开？
> 3.SD卡读卡器是否能够使用？我的SD卡读卡器卡槽坏掉了。

**Comment by David3434** [comment]
T450S
1 没影响到我使用，基本流畅
2 dw1820a不能打开，但是再次开启无线并睡眠，多搞几次，🈶️可以打开
3 目前没有这个卡，暂时无法测试

**Comment by David3434** [comment]
@CLAY-BIOS 
1.触摸板拖动文件和图标是否会有卡顿？(小红点在我的x250上使用时不是那么顺滑，有点僵硬感）
补充：这个可能是我的机器问题，发现在windowso 10下也有点僵硬感

**Comment by David3434** [comment]
大神好！
x250待机后再唤醒，偶尔鼠标会朝一个方向不停漂移，只好强制关机
t450s用得少，目前还没有发现
（用的是你最新Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore）

**Comment by CLAY-BIOS** [comment]
> 大神好！
> x250待机后再唤醒，偶尔鼠标会朝一个方向不停漂移，只好强制关机
> t450s用得少，目前还没有发现
> （用的是你最新Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore）

你试试这个，这是即将更新的版本。
[EFI.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-CLOVER/files/5693546/EFI.zip)

**Comment by David3434** [comment]
> > 大神好！
> > x250待机后再唤醒，偶尔鼠标会朝一个方向不停漂移，只好强制关机
> > t450s用得少，目前还没有发现
> > （用的是你最新Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore）
> 
> 你试试这个，这是即将更新的版本。
> [EFI.zip](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-CLOVER/files/5693546/EFI.zip)

刚刚试用了下，感觉小红点更滑顺了（也许是心理作用）
但是发现开机opencore界面触屏失效（影响不大）
感谢🙏

**Comment by David3434** [comment]
大神，新年好！
请问你的方案里删除一个文件怎么操作，delete键怎么用，总是搞不定，搜索了下，也没解决
祝：新年身体健康，万事如意 🤝
