### ISSUE TITLE
no bluetooth with BCM94360CS2

### ISSUE THREAD

**Issue by juanpy0223** [CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-CLOVER#7]
hello, how are you, Im using your EFI folder, on Catalina sometime it boots without bluetooth, but on Mojave and High Sierra I never get bluetooth... im using the BCM94360cs2 with ngff adapter (on my T450s)

![bcm94360cs2 wifi](https://user-images.githubusercontent.com/74636450/113090976-f972ea80-91b8-11eb-897a-1323f5347499.jpeg), 

![bcm94360cs2 adapter](https://user-images.githubusercontent.com/74636450/113090973-f7a92700-91b8-11eb-9c5a-6ffb589bdd17.jpeg)

**Comment by juanpy0223** [comment]
I also, have your OpenCore EFI, that works perfect, I just want to also understand Clover better

**Comment by CLAY-BIOS** [comment]
> I also, have your OpenCore EFI, that works perfect, I just want to also understand Clover better

This may be a USB problem
In Clover I use usbinjectall.kext to drive USB, which can cause some problems.
In OpenCore, I re-customized USB according to the original ACPI. You can try to delete the usbinjectall.kext in Clover, and then apply the ACPI patch in OpenCore (SSDT-XHCI-T450s. aml) to Clover

**Comment by juanpy0223** [comment]
thank you
